[2024-03-23T10:46:00.644+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: source_to_gcs.get_result_car_price_table manual__2024-03-23T10:30:17.118782+00:00 [queued]>
[2024-03-23T10:46:00.669+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: source_to_gcs.get_result_car_price_table manual__2024-03-23T10:30:17.118782+00:00 [queued]>
[2024-03-23T10:46:00.670+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 4
[2024-03-23T10:46:00.697+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_result_car_price_table> on 2024-03-23 10:30:17.118782+00:00
[2024-03-23T10:46:00.711+0000] {standard_task_runner.py:60} INFO - Started process 4725 to run task
[2024-03-23T10:46:00.721+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'source_to_gcs', 'get_result_car_price_table', 'manual__2024-03-23T10:30:17.118782+00:00', '--job-id', '326', '--raw', '--subdir', 'DAGS_FOLDER/sourcetobucket.py', '--cfg-path', '/tmp/tmpnl9s7j1n']
[2024-03-23T10:46:00.727+0000] {standard_task_runner.py:88} INFO - Job 326: Subtask get_result_car_price_table
[2024-03-23T10:46:00.819+0000] {task_command.py:423} INFO - Running <TaskInstance: source_to_gcs.get_result_car_price_table manual__2024-03-23T10:30:17.118782+00:00 [running]> on host ceb99a37e23c
[2024-03-23T10:46:00.970+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='source_to_gcs' AIRFLOW_CTX_TASK_ID='get_result_car_price_table' AIRFLOW_CTX_EXECUTION_DATE='2024-03-23T10:30:17.118782+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-23T10:30:17.118782+00:00'
[2024-03-23T10:46:00.977+0000] {sql.py:785} INFO - Executing SQL check: SELECT COUNT(*) from used_car_analysis_dataset.used_car_price LIMIT 1
[2024-03-23T10:46:01.003+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-23T10:46:01.007+0000] {base.py:83} INFO - Using connection ID 'gcp_***_conn' for task execution.
[2024-03-23T10:46:01.106+0000] {sql.py:457} INFO - Running statement: SELECT COUNT(*) from used_car_analysis_dataset.used_car_price LIMIT 1, parameters: None
[2024-03-23T10:46:01.109+0000] {bigquery.py:1613} INFO - Inserting job ***_1711190761108011_692f6613f62229254217b4d9e55504a9
[2024-03-23T10:46:01.578+0000] {sourcetobucket.py:87} ERROR - BigQuery check failed: 404 Not found: Table used-car-analysis:used_car_analysis_dataset.used_car_price was not found in location US; reason: notFound, message: Not found: Table used-car-analysis:used_car_analysis_dataset.used_car_price was not found in location US

Location: US
Job ID: ***_1711190761108011_692f6613f62229254217b4d9e55504a9

[2024-03-23T10:46:01.579+0000] {python.py:202} INFO - Done. Returned value was: CAR_PRICE_TABLE_not_found
[2024-03-23T10:46:01.632+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=source_to_gcs, task_id=get_result_car_price_table, execution_date=20240323T103017, start_date=20240323T104600, end_date=20240323T104601
[2024-03-23T10:46:01.706+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-23T10:46:01.779+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
