[2024-03-23T10:37:34.096+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: source_to_gcs.get_result_car_price_table manual__2024-03-23T10:30:17.118782+00:00 [queued]>
[2024-03-23T10:37:34.116+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: source_to_gcs.get_result_car_price_table manual__2024-03-23T10:30:17.118782+00:00 [queued]>
[2024-03-23T10:37:34.117+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-03-23T10:37:34.140+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): get_result_car_price_table> on 2024-03-23 10:30:17.118782+00:00
[2024-03-23T10:37:34.151+0000] {standard_task_runner.py:60} INFO - Started process 4591 to run task
[2024-03-23T10:37:34.159+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'source_to_gcs', 'get_result_car_price_table', 'manual__2024-03-23T10:30:17.118782+00:00', '--job-id', '320', '--raw', '--subdir', 'DAGS_FOLDER/sourcetobucket.py', '--cfg-path', '/tmp/tmpqtysd48y']
[2024-03-23T10:37:34.164+0000] {standard_task_runner.py:88} INFO - Job 320: Subtask get_result_car_price_table
[2024-03-23T10:37:34.243+0000] {task_command.py:423} INFO - Running <TaskInstance: source_to_gcs.get_result_car_price_table manual__2024-03-23T10:30:17.118782+00:00 [running]> on host ceb99a37e23c
[2024-03-23T10:37:34.406+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='source_to_gcs' AIRFLOW_CTX_TASK_ID='get_result_car_price_table' AIRFLOW_CTX_EXECUTION_DATE='2024-03-23T10:30:17.118782+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-23T10:30:17.118782+00:00'
[2024-03-23T10:37:34.411+0000] {sql.py:785} INFO - Executing SQL check: SELECT COUNT(*) from used_car_analysis_dataset.used_car_price LIMIT 1
[2024-03-23T10:37:34.425+0000] {connection.py:269} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-03-23T10:37:34.429+0000] {base.py:83} INFO - Using connection ID 'gcp_***_conn' for task execution.
[2024-03-23T10:37:34.498+0000] {sql.py:457} INFO - Running statement: SELECT COUNT(*) from used_car_analysis_dataset.used_car_price LIMIT 1, parameters: None
[2024-03-23T10:37:34.501+0000] {bigquery.py:1613} INFO - Inserting job ***_1711190254500014_692f6613f62229254217b4d9e55504a9
[2024-03-23T10:37:34.907+0000] {sourcetobucket.py:87} ERROR - BigQuery check failed: 404 Not found: Table used-car-analysis:used_car_analysis_dataset.used_car_price was not found in location US; reason: notFound, message: Not found: Table used-car-analysis:used_car_analysis_dataset.used_car_price was not found in location US

Location: US
Job ID: ***_1711190254500014_692f6613f62229254217b4d9e55504a9

[2024-03-23T10:37:34.908+0000] {python.py:202} INFO - Done. Returned value was: CAR_PRICE_TABLE_not_found
[2024-03-23T10:37:34.953+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=source_to_gcs, task_id=get_result_car_price_table, execution_date=20240323T103017, start_date=20240323T103734, end_date=20240323T103734
[2024-03-23T10:37:35.018+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-23T10:37:35.079+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
